name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: agent
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Convert repository to lowercase
        id: lowercase
        run: |
          echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.repository }}:latest
            ghcr.io/${{ steps.lowercase.outputs.repository }}:${{ github.sha }}
      
      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository using HTTPS URL without token
          git clone https://github.com/Akhil10/grade-api-gitops.git gitops
          cd gitops
          
          if [[ "$OSTYPE" == "darwin"* ]]; then
             sed -i '' "s|image: ghcr.io/${{ steps.lowercase.outputs.repository }}:.*|image: ghcr.io/${{ steps.lowercase.outputs.repository }}:${{ github.sha }}|g" deployment.yaml
          else
             sed -i "s|image: ghcr.io/${{ steps.lowercase.outputs.repository }}:.*|image: ghcr.io/${{ steps.lowercase.outputs.repository }}:${{ github.sha }}|g" deployment.yaml
          fi
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          # Push
          git push -f https://${GIT_TOKEN}@github.com/Akhil10/grade-api-gitops.git main
